title: Nancy Ping
description: Data visualization, Video editing, Graphic Design, Writing, and of course Social Justice
author: Nancy Ping
github: https://github.com/nancyping-report
about: Journalism Graduate <a href="https://camd.northeastern.edu/" target="_blank">@Northeastern University</a> 
Research Member <a href="http://sites.bu.edu/aiem/people/" target="_blank">@Boston Univeristy AIEM group</a> 
Former Reporter <a href="https://thescopeboston.org/" target="_blank">@theScopeBoston</a> 
Author <a href="https://thescopeboston.org/" target="_blank">@Storybench</a> 

disqus_shortname: programming
#google_analytics: UA-31048387-6
avatar_url: /static/img/me.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:

    - icon: fa-github
      link: "https://github.com/nancyping-report"

share:
  twitter_username: @nancyping2
  # fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Blogs
      url: /blogs/
    - text: XML Feed
      url: /feed.xml
# url: "http://localhost:4000"
url: "https://tmjam.github.io/tauseef-blog"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/blogs/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
